### PR TITLE
Include and use jaguar jsdoc template.

### PR DESCRIPTION
**Pull request by caufang**
This will use the jaguar template for the jsdoc output HTML.

### CODE REVIEW

**Comment by justinhelmer** [comment]
This will not work as-is because the path will be relative to the current working directory. `path.resolve` exists to help mitigate this.

**Comment by justinhelmer** [comment]
made changes and merged.

**Comment by caufang** [comment]
I had been using a path that would work from the jsdoc install location in GRM based on the search locations that jsdoc uses when given a template path: https://github.com/jsdoc3/jsdoc/issues/543#issuecomment-29645334

The template path provided in jsdoc.js was making the assumption that jsdoc and the jaguar template would be installed as sibling directories.

Is `path.resolve()` with the supplied argument going to have any issues when the `node_modules` location changes with `npm` versions?

**Comment by justinhelmer** [comment]
Even when installed as sibling directories, when run from a third party module running `GRM`, the path was internally being resolved to:

> [3rd party module root]/node_modules/gh-release-manager/lib/jaguarjs-jsdoc

...which does not exist.

It was causing the script to throw a `FATAL` error, and the result was that the docs were not being generated.

`path.resolve()` generates an _absolute_ path, and since this package restricts the expected `node` version, the assumption is that `npm 2.x` is installed and thus, the path would be correct.

There are other instances that assume `npm 2.x` is installed, all of which will have to be addressed when supporting the `5.x` branch of node, which is packaged with `npm 3.x`.

**Comment by caufang** [comment]
That's really weird because it was generating documentation for me without errors.

I was running this as part of the .io site rather than GRM stand-alone, do you think that could have made some difference?

**Comment by justinhelmer** [comment]
That is interesting. There are a few things I can think of:
- The `grm` tool may have been running from a directory other than `./node_modules/gh-release-manager/bin/grm.js`. This is possible, for example, if `grm` is checked out and [linked](https://docs.npmjs.com/cli/link).
- The `jaguar-jsdoc` module was installed as a _sibling_ to the 3rd party module using `grm`.
- The [path check](https://github.com/jsdoc3/jsdoc/issues/543#issuecomment-29645334) you referenced run by `jsdoc` may fall into different logical blocks depending on `OS`, or some other discrete environment difference.

One way to be sure is to point to the checked-out version of `grm` with the changes you want to test.

In the `package.json` of the 3rd party module:

``` js
devDependencies: {
  "gh-release-manager": "caufang/gh-release-manager"
}
```

When running `npm install`, you can test the third party module against what would be the merged version of `grm` with the suggested change (assuming it is not already installed).

**Comment by caufang** [comment]
I had `jaguar-jsdoc` installed in the `node_modules` dir that was within `grm`, which made it a sibling to `jsdoc`.

Only thing I can think of is that the relative path "../jaguar-jsdoc" was falling to the last case of the 3 search paths: "The JSDoc directory".

**Pull request merged**
